#  Main header!
#  Line 2

[songs]
	[songs.house]
		triggers = [ "Zones-pavia" ]
		volume = "0.75"

[triggers]
	[triggers.universal]
		active_cooldown = "0"
		fade_in = "20"
		fade_out = "20"
		persistence = "0"
		ticks_before_active = "0"
		ticks_before_audio = "0"
		ticks_between_audio = "0"
		play_when_paused = "true"
	[triggers.zones]
		identifier = "pavia"
		zone_max_x = "10000"
		zone_max_y = "300"
		zone_max_z = "10000"
		zone_min_x = "-10000"
		zone_min_y = "-100"
		zone_min_z = "-10000"

